# Generated by Django 5.1.3 on 2025-09-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_weatherdata_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weatherrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
