# Generated by Django 5.1.3 on 2025-09-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_weatherdata_city_alter_weatherrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='condition',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
